version: "3.7"
services:
  app:
    container_name: fake_prime_backend_app
    build:
      context: .
      args:
        NODE_VERSION: 8.12.0
    networks:
      - reverse_proxy
    ports:
      - "3005:80"
    labels:
      - traefik.backend=fake_wallet_backend
      - traefik.frontend.rule=Host:fake-wallet-backend.testdev.com
      - traefik.docker.network=reverse_proxy
      - traefik.port=80
    restart: always
networks:
  reverse_proxy:
    external: true
