version: "3.7"
services:
  app:
    container_name: fake_prime_backend_app
    build:
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
    networks:
      - reverse_proxy
    ports:
      - "3005:${EXPRESS_PORT}"
    labels:
      - traefik.backend=fake_prime_backend
      - traefik.frontend.rule=Host:fake-prime-backend.bayo.my
      - traefik.docker.network=reverse_proxy
      - traefik.port=3001
    restart: always
networks:
  reverse_proxy:
    external: true
